### ISSUE TITLE
Add link to live website in readme

### ISSUE THREAD

**Issue by fritzrehde** [TylerBloom/avid-rustacean#9]
Hi, I really like Rust, TUIs (and therefore also `ratatui`, of course) and Rust frontend frameworks (I still need to do some more exploring on that front, though), so this project combining all of those seems absolutely awesome!
I came here from [ratatui's LinkedIn post](https://www.linkedin.com/posts/ratatui-rs_here-is-a-tui-based-dev-blog-built-with-ratatui-activity-7142124544105914368-eStI?utm_source=share&utm_medium=member_desktop), and was a little sad to see that https://avid-rustacean.shuttleapp.rs/ is currently not live. I'm sure you know the website isn't live yourself, just wanted to chime in and suggest maybe adding a link to it in the readme or in some other way once it's ready and deployed.
Looking forward to exploring this project further! Great work!

**Comment by TylerBloom** [comment]
Thanks! Actually, I was unaware that the site was down. Because Shuttle is still in beta, the project often requires restarts. A link to the project in the README is certainly in order. This is also somewhat related to #2 , which would give me better insight to when the site is down.

At any rate, I'm glad that you like the project!

**Comment by orhun** [comment]
Ex-Shuttle team member here 👋🏼 

It would help if you set the `--idle-minutes` to `0` when you do `cargo shuttle project start` (if you aren't doing this already)

Also, `cargo shuttle project restart` might help in the case of downtime.

**Comment by TylerBloom** [comment]
@fritzrehde , I've added a link to the description of the Github repo and added a deployment status banner to the README. If this is good enough for you, would you mind closing this ticket?

**Comment by fritzrehde** [comment]
Yup, adding a link in the GitHub description is exactly what I had in mind! Looking forward to checking this out!
